TOKEN = 'your_token'
CHAT_ID = 'your_group_id'
ADMIN_CHAT_ID = 'your_admin_id'
ALLOWED_IDS = [your_group_id, your_admin_id]
REACTIONS = ["🔥", "👍", "🤮", "😢", "🤡", "😁", "🍌", "👎"]
MAX_USAGE = 2
RESET_TIME_SECONDS = 300
TODOLIST_ID = 0
ADMINS_ID = [your_admin_id]
